# Generated by Django 5.2.15 on 2026-06-11 08:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pg_trgm"),  # extension must exist before the indexes
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="decisionrecord",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="decision_title_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="project_name_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
