# Generated by Django 5.2.15 on 2026-06-11 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_decisionrecord_decision_title_trgm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="color",
            field=models.CharField(
                default="#4f46e5",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Use a #rrggbb hex color."
                    )
                ],
            ),
        ),
    ]
