# Generated by Django 5.2.15 on 2026-06-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pg_trgm"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="page",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
