# Generated by Django 5.2.15 on 2026-09-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_achievements"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("login_ok", "Login"),
                            ("login_failed", "Failed login"),
                            ("login_locked", "Login locked out"),
                            ("api_key_rejected", "API key rejected"),
                        ],
                        max_length=24,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=64)),
                ("user_agent", models.CharField(blank=True, max_length=200)),
                ("detail", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
