# Generated by Django 5.2.15 on 2026-09-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_access_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
