# Generated by Django 5.2.15 on 2026-09-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_feed_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="souls_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
