# Generated by Django 5.2.15 on 2026-09-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_pet_souls_since"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("media_files", models.PositiveIntegerField(default=0)),
                ("database", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
