# Generated by Django 5.2.15 on 2026-09-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_backup_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
