# Generated by Django 5.2.15 on 2026-09-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_todo_due_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
