# Generated by Django 5.2.17 on 2026-09-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_todoitem_repeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
