# Generated by Django 5.2.17 on 2026-09-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="blocked_by",
            field=models.ManyToManyField(
                blank=True, related_name="blocks", to="plans.milestone"
            ),
        ),
    ]
