# Generated by Django 5.2.17 on 2026-09-14 20:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_milestone_blocked_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="MilestoneDateChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reason", models.CharField(blank=True, max_length=300)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_changes",
                        to="plans.milestone",
                    ),
                ),
            ],
            options={
                "ordering": ["changed_at", "pk"],
            },
        ),
    ]
