# Generated by Django 5.2.17 on 2026-09-14 22:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_milestonedatechange"),
        ("projects", "0004_projecttemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("kept", models.PositiveIntegerField(default=0)),
                ("completed", models.PositiveIntegerField(default=0)),
                ("moved", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_reviews",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at", "-pk"],
            },
        ),
    ]
