# Generated by Django 5.2.15 on 2026-06-10 21:54

import django.db.models.deletion
import literature.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doi",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("arxiv_id", models.CharField(blank=True, default="", max_length=50)),
                (
                    "openalex_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("bibtex_key", models.CharField(max_length=120, unique=True)),
                ("entry_type", models.CharField(default="article", max_length=30)),
                ("title", models.TextField()),
                ("authors", models.JSONField(default=list)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, max_length=300)),
                ("abstract", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=literature.models.reference_pdf_path,
                    ),
                ),
                ("raw_bibtex", models.TextField(blank=True)),
                ("extra", models.JSONField(default=dict)),
                ("citation_count", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reading_status",
                    models.CharField(
                        choices=[
                            ("to_read", "To read"),
                            ("skimmed", "Skimmed"),
                            ("read", "Read"),
                            ("annotated", "Annotated"),
                        ],
                        default="to_read",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_references",
                        to="projects.project",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_links",
                        to="literature.reference",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "reference"),
                        name="unique_reference_per_project",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CitationEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cited",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_citations",
                        to="literature.reference",
                    ),
                ),
                (
                    "citing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_citations",
                        to="literature.reference",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("citing", "cited"), name="unique_citation_edge"
                    )
                ],
            },
        ),
    ]
