# Generated by Django 5.2.15 on 2026-06-10 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitationSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Never synced"),
                            ("syncing", "Syncing"),
                            ("done", "Synced"),
                            ("failed", "Failed"),
                        ],
                        default="idle",
                        max_length=10,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.CharField(blank=True, max_length=300)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citation_sync",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
