# Generated by Django 5.2.15 on 2026-06-10 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0002_citationsyncstate"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_themes",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReviewMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "project_reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_marks",
                        to="literature.projectreference",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="literature.reviewtheme",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="reviewtheme",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_theme_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewmark",
            constraint=models.UniqueConstraint(
                fields=("theme", "project_reference"), name="unique_mark_per_cell"
            ),
        ),
    ]
