# Generated by Django 5.2.15 on 2026-06-11 08:16

import django.contrib.postgres.indexes
from django.db import migrations

from core.migration_ops import PostgresAddIndex


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pg_trgm"),  # extension must exist before the indexes
        ("literature", "0003_reviewtheme_reviewmark_and_more"),
    ]

    operations = [
        PostgresAddIndex(
            model_name="reference",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="reference_title_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
