# Generated by Django 5.2.15 on 2026-09-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0004_reference_reference_title_trgm"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60, unique=True)),
                ("color", models.CharField(blank=True, max_length=7)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SavedView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("params", models.JSONField(default=dict)),
                ("position", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.AddField(
            model_name="reference",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="references", to="literature.librarytag"
            ),
        ),
    ]
