# Generated by Django 5.2.15 on 2026-09-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0006_highlight"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(blank=True, max_length=500)),
                ("pages", models.JSONField(default=list)),
                ("body", models.TextField(blank=True)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("char_count", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("extracted_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text",
                        to="literature.reference",
                    ),
                ),
            ],
        ),
    ]
