# Generated by Django 5.2.15 on 2026-09-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0007_referencetext"),
    ]

    operations = [
        migrations.AddField(
            model_name="highlight",
            name="rects",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
