# Generated by Django 5.2.17 on 2026-09-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0010_reading_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="retraction_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="retraction_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="retraction_kind",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="reference",
            name="retraction_notice",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
