# Generated by Django 5.2.17 on 2026-09-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0011_retraction_watch"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="published_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="published_doi",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="reference",
            name="published_venue",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
