# Generated by Django 5.2.17 on 2026-09-15 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0012_preprint_watch"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="cited_by_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CitingWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("openalex_id", models.CharField(max_length=50, unique=True)),
                ("doi", models.CharField(blank=True, default="", max_length=255)),
                ("title", models.TextField()),
                ("authors", models.JSONField(default=list)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("published_on", models.DateField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, default="", max_length=300)),
                ("cited_by_count", models.PositiveIntegerField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cites",
                    models.ManyToManyField(
                        related_name="citing_works", to="literature.reference"
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citing_matches",
                        to="literature.reference",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_on", "-created_at"],
            },
        ),
    ]
