# Generated by Django 5.2.17 on 2026-09-15 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0013_citation_watch"),
        ("projects", "0004_projecttemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=500, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=300)),
                ("site_url", models.URLField(blank=True, default="", max_length=500)),
                ("etag", models.CharField(blank=True, default="", max_length=200)),
                (
                    "last_modified",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("last_ok_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feeds",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
            },
        ),
        migrations.CreateModel(
            name="FeedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guid", models.CharField(max_length=500)),
                ("title", models.TextField()),
                ("authors", models.JSONField(default=list)),
                ("summary", models.TextField(blank=True, default="")),
                ("link", models.URLField(blank=True, default="", max_length=500)),
                ("doi", models.CharField(blank=True, default="", max_length=255)),
                ("arxiv_id", models.CharField(blank=True, default="", max_length=50)),
                ("published_on", models.DateField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="literature.feed",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feed_items",
                        to="literature.reference",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_on", "pk"],
                "indexes": [
                    models.Index(fields=["doi"], name="literature__doi_18d84e_idx"),
                    models.Index(
                        fields=["arxiv_id"], name="literature__arxiv_i_8287d7_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feed", "guid"), name="literature_feeditem_guid"
                    )
                ],
            },
        ),
    ]
