# Generated by Django 5.2.17 on 2026-09-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0014_feeds"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="notices",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
