# Generated by Django 5.2.17 on 2026-09-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0015_notices"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="mute",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="feed",
            name="muted_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="muted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="muted_by",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
