# Generated by Django 5.2.17 on 2026-09-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0016_feed_mute"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="pdf_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="pdf_source",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
