# Generated by Django 5.2.15 on 2026-06-10 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("literature", "0002_citationsyncstate"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=400)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idea", "Idea"),
                            ("outlining", "Outlining"),
                            ("drafting", "Drafting"),
                            ("internal_review", "Internal review"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("revision", "Revision"),
                            ("accepted", "Accepted"),
                            ("published", "Published"),
                            ("shelved", "Shelved"),
                        ],
                        default="idea",
                        max_length=20,
                    ),
                ),
                ("target_venue", models.CharField(blank=True, max_length=300)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("abstract", models.TextField(blank=True)),
                ("repo_url", models.URLField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manuscripts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ManuscriptReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cite_key_override", models.CharField(blank=True, max_length=120)),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="writing.manuscript",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="literature.reference",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="manuscript",
            name="references",
            field=models.ManyToManyField(
                blank=True,
                through="writing.ManuscriptReference",
                to="literature.reference",
            ),
        ),
        migrations.CreateModel(
            name="SubmissionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("desk_reject", "Desk reject"),
                            ("reviews_received", "Reviews received"),
                            ("revision_submitted", "Revision submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                            ("note", "Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="writing.manuscript",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="manuscriptreference",
            constraint=models.UniqueConstraint(
                fields=("manuscript", "reference"),
                name="unique_reference_per_manuscript",
            ),
        ),
    ]
