# Generated by Django 5.2.15 on 2026-06-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="latex_source",
            field=models.TextField(blank=True),
        ),
    ]
