# Generated by Django 5.2.15 on 2026-06-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0002_manuscript_latex_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="compile_log",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="compile_status",
            field=models.CharField(
                choices=[
                    ("idle", "Not compiled"),
                    ("running", "Compiling…"),
                    ("ok", "Compiled"),
                    ("failed", "Failed"),
                ],
                default="idle",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="compiled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="compiled_pdf",
            field=models.FileField(blank=True, null=True, upload_to="manuscripts/pdf/"),
        ),
    ]
