# Generated by Django 5.2.15 on 2026-06-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0003_manuscript_compile_log_manuscript_compile_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="compile_diagnostics",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
