# Generated by Django 5.2.15 on 2026-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0004_manuscript_compile_diagnostics"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="compile_generation",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
