# Generated by Django 5.2.15 on 2026-06-11 18:49

import django.db.models.deletion
import writing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0005_manuscript_compile_generation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManuscriptFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "path",
                    models.CharField(
                        max_length=200,
                        validators=[writing.models.validate_manuscript_path],
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tex", "LaTeX"),
                            ("bib", "BibTeX"),
                            ("asset", "Asset"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "asset",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=writing.models.manuscript_asset_path,
                    ),
                ),
                ("is_main", models.BooleanField(default=False)),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="writing.manuscript",
                    ),
                ),
            ],
            options={
                "ordering": ["path"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("manuscript", "path"), name="unique_path_per_manuscript"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_main", True)),
                        fields=("manuscript",),
                        name="unique_main_file_per_manuscript",
                    ),
                ],
            },
        ),
    ]
