# Generated by Django 5.2.15 on 2026-06-12 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_content_document_kind_document_rel_path_and_more"),
        ("writing", "0008_manuscriptrevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="root_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.folder",
            ),
        ),
    ]
