# Generated by Django 5.2.15 on 2026-09-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0011_materialize_manuscript_tree"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="venue_limits",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
