# Generated by Django 5.2.15 on 2026-09-07 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0013_manuscript_synctex"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordCountSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("words", models.PositiveIntegerField(default=0)),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_samples",
                        to="writing.manuscript",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("manuscript", "date"), name="one_word_sample_per_day"
                    )
                ],
            },
        ),
    ]
