# Generated by Django 5.2.15 on 2026-09-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0014_word_count_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="compiled_bbl",
            field=models.TextField(blank=True),
        ),
    ]
