# Generated by Django 5.2.15 on 2026-09-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0015_manuscript_compiled_bbl"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="compile_source_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="compiled_source_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
