# Generated by Django 5.2.15 on 2026-09-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0016_compile_source_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="auto_revisions_keep",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
