# Generated by Django 5.2.15 on 2026-06-11 08:16

import django.contrib.postgres.indexes
from django.db import migrations

from core.migration_ops import PostgresAddIndex


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pg_trgm"),  # extension must exist before the indexes
        ("literature", "0004_reference_reference_title_trgm"),
        ("notes", "0002_note_notelink_note_unique_note_title_per_project_and_more"),
        ("projects", "0002_decisionrecord_decision_title_trgm_and_more"),
    ]

    operations = [
        PostgresAddIndex(
            model_name="note",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="note_title_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
