# Generated by Django 5.2.15 on 2026-09-07 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0002_botrun"),
        ("notes", "0003_note_note_title_trgm"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickcapture",
            name="bot_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captures",
                to="bots.botrun",
            ),
        ),
    ]
