# Generated by Django 5.2.17 on 2026-09-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_capture_bot_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickcapture",
            name="snoozed_until",
            field=models.DateField(blank=True, null=True),
        ),
    ]
