# Generated by Django 5.2.17 on 2026-09-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_capture_snoozed_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickcapture",
            name="became_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quickcapture",
            name="became_kind",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="quickcapture",
            name="triaged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
