# Generated by Django 5.2.17 on 2026-09-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_capture_became"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickcapture",
            name="link_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quickcapture",
            name="link_title",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
