# Generated by Django 5.2.15 on 2026-06-11 08:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pg_trgm"),  # extension must exist before the indexes
        ("documents", "0001_initial"),
        ("projects", "0002_decisionrecord_decision_title_trgm_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="document_title_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
