# Generated by Django 5.2.15 on 2026-06-12 22:09

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_document_title_trgm"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="document",
            name="kind",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="document",
            name="rel_path",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="document",
            name="role",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("manuscript_source", "Manuscript source"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True, upload_to=documents.models.project_document_path
            ),
        ),
    ]
