# Generated by Django 5.2.17 on 2026-09-16 08:02

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_content_document_kind_document_rel_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to=documents.models.document_version_path
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("upload", "Replaced by an upload"),
                            ("edit", "Edited in place"),
                            ("write", "Written by the API or Claude"),
                            ("restore", "Restored an earlier version"),
                        ],
                        default="upload",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "number"),
                        name="documentversion_number_per_document",
                    )
                ],
            },
        ),
    ]
