# Generated by Django 5.2.17 on 2026-09-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_derive_kinds"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
