# Generated by Django 5.2.15 on 2026-06-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, unique=True)),
                ("body", models.TextField()),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated, e.g. writing, lit-review",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
