# Generated by Django 5.2.17 on 2026-09-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="last_used_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="prompt",
            name="use_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
