# Generated by Django 5.2.17 on 2026-09-19 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0003_prompt_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="next",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous",
                to="prompts.prompt",
            ),
        ),
    ]
