# Generated by Django 5.2.15 on 2026-06-10 22:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("literature", "0002_citationsyncstate"),
        ("notes", "0002_note_notelink_note_unique_note_title_per_project_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=500)),
                ("version", models.CharField(blank=True, max_length=60)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Hypothesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("statement", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("testing", "Testing"),
                            ("supported", "Supported"),
                            ("contradicted", "Contradicted"),
                            ("inconclusive", "Inconclusive"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hypotheses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "hypotheses",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="ExperimentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=datetime.date.today)),
                ("title", models.CharField(max_length=300)),
                ("body", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiment_entries",
                        to="projects.project",
                    ),
                ),
                (
                    "hypotheses",
                    models.ManyToManyField(
                        blank=True, related_name="experiments", to="research.hypothesis"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "experiment entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("supports", "Supports"),
                            ("contradicts", "Contradicts"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("summary", models.TextField()),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence",
                        to="documents.document",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence",
                        to="notes.note",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence",
                        to="literature.reference",
                    ),
                ),
                (
                    "hypothesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="research.hypothesis",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "evidence",
                "ordering": ["-created_at"],
            },
        ),
    ]
