# Generated by Django 5.2.15 on 2026-06-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimententry",
            name="commit_url",
            field=models.URLField(blank=True),
        ),
    ]
