# Generated by Django 5.2.15 on 2026-06-16 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_protocol"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimententry",
            name="protocol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="experiments",
                to="research.protocol",
            ),
        ),
    ]
